import type { GalleryItem } from "@/lib/content/types";
import { published } from "@/lib/content/static/seed-utils";

/**
 * Seed gallery items.
 *
 * `url` is null throughout, so every tile renders designed placeholder art keyed
 * to its own title. Uploading real media through the CMS — or setting `url` here
 * — replaces the artwork with no other change required.
 */
const seed = [
  {
    id: "gal-01",
    title: "First wing test, Kyeleni Secondary",
    caption: "The moment a paper wing generates measurable lift.",
    category: "School Visits",
    mediaType: "image",
    aspectRatio: "landscape",
    takenAt: "2026-03-12",
    location: "Machakos",
    sortOrder: 1,
  },
  {
    id: "gal-02",
    title: "Approach into Nairobi",
    caption: "A Form Three student flies her third approach — and lands it.",
    category: "Students",
    mediaType: "image",
    aspectRatio: "portrait",
    takenAt: "2026-03-12",
    location: "Machakos",
    sortOrder: 2,
  },
  {
    id: "gal-03",
    title: "Turnaround, minute forty-two",
    caption: "Three minutes left and the loadsheet has not been signed.",
    category: "Events",
    mediaType: "image",
    aspectRatio: "landscape",
    takenAt: "2026-05-08",
    location: "Machakos",
    sortOrder: 3,
  },
  {
    id: "gal-04",
    title: "Inside the hangar",
    caption: "A licensed engineer explains what a Certificate of Release to Service means.",
    category: "Aircraft",
    mediaType: "image",
    aspectRatio: "landscape",
    takenAt: "2026-04-02",
    location: "Mombasa",
    sortOrder: 4,
  },
  {
    id: "gal-05",
    title: "Chart work",
    caption: "Nairobi to Kisumu, plotted by hand, wind correction applied.",
    category: "School Visits",
    mediaType: "image",
    aspectRatio: "square",
    takenAt: "2026-07-11",
    location: "Kisumu",
    sortOrder: 5,
  },
  {
    id: "gal-06",
    title: "Questions after Sky Talk",
    caption: "The queue that forms when the slides stop.",
    category: "Students",
    mediaType: "image",
    aspectRatio: "portrait",
    takenAt: "2026-07-11",
    location: "Kisumu",
    sortOrder: 6,
  },
  {
    id: "gal-07",
    title: "Turboprop on the apron",
    caption: "The regional fleet that connects the counties.",
    category: "Aircraft",
    mediaType: "image",
    aspectRatio: "landscape",
    takenAt: "2026-06-14",
    location: "Nairobi",
    sortOrder: 7,
  },
  {
    id: "gal-08",
    title: "Survey flight, school field",
    caption: "A licensed remote pilot maps the school in eleven minutes.",
    category: "School Visits",
    mediaType: "image",
    aspectRatio: "landscape",
    takenAt: "2026-09-03",
    location: "Nyeri",
    sortOrder: 8,
  },
  {
    id: "gal-09",
    title: "Preparing teaching materials for a school visit",
    caption: "The team prepares classroom resources before travelling to the school.",
    category: "Behind the Scenes",
    mediaType: "image",
    aspectRatio: "portrait",
    takenAt: "2026-02-19",
    location: "Nairobi",
    sortOrder: 9,
  },
  {
    id: "gal-10",
    title: "Open Day, main hall",
    caption: "Two hundred and forty students, fourteen career stands.",
    category: "Events",
    mediaType: "image",
    aspectRatio: "landscape",
    takenAt: "2026-09-19",
    location: "Nairobi",
    sortOrder: 10,
  },
  {
    id: "gal-11",
    title: "The weather brief",
    caption: "Crosswind of 22 knots. Limit is 25. Do you go?",
    category: "School Visits",
    mediaType: "image",
    aspectRatio: "square",
    takenAt: "2026-08-07",
    location: "Nakuru",
    sortOrder: 11,
  },
  {
    id: "gal-12",
    title: "Control tower visit",
    caption: "Watching separation being maintained in real time.",
    category: "Events",
    mediaType: "image",
    aspectRatio: "portrait",
    takenAt: "2026-10-08",
    location: "Nairobi",
    sortOrder: 12,
  },
  {
    id: "gal-13",
    title: "How a wing stalls",
    caption: "A ninety-second explainer filmed during the Flight Lab.",
    category: "Behind the Scenes",
    mediaType: "video",
    aspectRatio: "landscape",
    takenAt: "2026-05-22",
    location: "Nairobi",
    sortOrder: 13,
  },
  {
    id: "gal-14",
    title: "Cockpit walkthrough",
    caption: "A first officer explains the instrument scan.",
    category: "Aircraft",
    mediaType: "video",
    aspectRatio: "landscape",
    takenAt: "2026-06-18",
    location: "Nairobi",
    sortOrder: 14,
  },
  {
    id: "gal-15",
    title: "Career mapping clinic",
    caption: "Subjects in, pathway out.",
    category: "Students",
    mediaType: "image",
    aspectRatio: "landscape",
    takenAt: "2026-11-14",
    location: "Mombasa",
    sortOrder: 15,
  },
  {
    id: "gal-16",
    title: "Packing down",
    caption: "Sixteen schools, one van, and a great deal of tape.",
    category: "Behind the Scenes",
    mediaType: "image",
    aspectRatio: "square",
    takenAt: "2026-10-09",
    location: "Kitui",
    sortOrder: 16,
  },
] as const;

export const galleryItems: GalleryItem[] = seed.map((item) => ({
  ...item,
  url: null,
  videoUrl: null,
  ...published(),
}));
